/** @jsxRuntime classic */
/** @jsx jsx */
import { css, jsx } from '@emotion/react';
import React, { Fragment } from 'react';
import Head from 'next/head';
import Link from 'next/link'

import Button from '@atlaskit/button';
import Form, { Field, FormFooter, HelperMessage } from '@atlaskit/form';
import Textfield from '@atlaskit/textfield';
import TextArea from '@atlaskit/textarea';

import Layout from '../../components/layout';

import { GoogleLogin, GoogleLogout } from 'react-google-login';

const CLIENT_ID = '191905327905-uorckd587olhphs49chlpc69o7gqj7l5.apps.googleusercontent.com';

const buttonStyles = css({
  margin: '18px',
})

const cancelButtonStyle = css({
  marginLeft: '10px',
})

const formTitleStyles = css({
    font: 'SF Pro',
    fontSize: 24,
    fontWeight: 'medium',
    paddingBottom: '20px',
    paddingTop: '50px',
})

const itineraryFormStyle = css({
  display: 'flex',
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center'
});

const titleStyle = {
  display: 'flex',
  maxWidth: '100%',
  margin: '0 auto',
  flexDirection: 'column'
}

const formStyle = {
  display: 'flex',
  width: '400px',
  maxWidth: '100%',
  margin: '0 auto',
  flexDirection: 'column'
}

const fieldStyle = {
  paddingBottom: '100px'
}



export default function CreateAccount() {
  return (
    <Layout pageTitle="Itinerary Creator">
        <Head>
            <title>Create Itinerary</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
          
          <div
            style={formStyle}
          >
            
          <div css={ formTitleStyles }>Create account</div>
            <Form
            onSubmit={() =>
                console.log('form submitted')
            }
            >
            {({ formProps }) => (
                <form {...formProps}>
                    <Field label="Email" name="example-text">
                        {({ fieldProps }) => (
                        <Fragment>
                            <Textfield
                            placeholder="Enter your email"
                            {...fieldProps}
                            />
                        </Fragment>
                        )}
                    </Field>
                    
                    <Field label="Password" name="enterPassword">
                        {({ fieldProps }) => (
                        <Fragment>
                            <Textfield
                            placeholder="Enter password"
                            {...fieldProps}
                            />
                        </Fragment>
                        )}
                    </Field>

                    <Field label="Re-enter Password" name="reenterPasswordDetails">
                        {({ fieldProps }) => (
                        <Fragment>
                            <Textfield
                            placeholder="Re-enter password"
                            {...fieldProps}
                            />
                        </Fragment>
                        )}
                    </Field>

                    <FormFooter>
                      <Button shouldFitContainer appearance="primary">
                        Create account
                      </Button>
                    </FormFooter>
                </form>  
            )}
            </Form>
            <div style={{paddingTop: '20px'}}></div>
            <GoogleLogin
              clientId={CLIENT_ID}
              buttonText='Create account with Google'
            />
          </div>

          
    </Layout>
  )
}