/** @jsxRuntime classic */
/** @jsx jsx */
import { css, jsx } from '@emotion/react';
import Head from 'next/head';

import Link from 'next/link'

import Image from 'next/image';

import Button from '@atlaskit/button';

import React, { useState, useEffect } from 'react';
import Textfield from '@atlaskit/textfield';
import Form, { Field, FormFooter, HelperMessage } from '@atlaskit/form';
import { Checkbox } from '@atlaskit/checkbox';
import Avatar from '@atlaskit/avatar';
import { RadioGroup } from '@atlaskit/radio';


import Layout from '../../components/layout';
import VaccinationForm from '../../components/vaccinationForm';

import { useSession } from 'next-auth/react';
import { getProfileData } from '../../lib/util';

const informationStyles = css({
  font: 'SF Pro',
  fontSize: 16,
  paddingBottom: '30px',
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
});

const profileTitleStyles = css({
  font: 'SF Pro',
  fontSize: 28,
  alignSelf: 'center',
  fontWeight: 'bold',
  paddingBottom: '50px',
});

const profileContainerStyles = {
  display: 'flex',
  width: '400px',
  maxWidth: '100%',
  margin: '0 auto',
  flexDirection: 'column',
  justifyContent: 'center',
}

const avatarPosition = {
  display: 'flex',
  width: '400px',
  maxWidth: '100%',
  margin: '0 auto',
  flexDirection: 'column',
  justifyContent: 'center',
  alignItems: 'center',
  paddingBottom: '10px',
};

export default function AccountDetails() {
  const { data: session } = useSession()

  const [vaccinationStatus, setvaccinationStatus] = useState();

  useEffect(async () => {
    if (session) {
      const user = await getProfileData(session.user.email)
      setvaccinationStatus(user.vaccination);
    }
  },[session]);

  return (
    <Layout pageTitle="Account Details" signInRequired>
      <Head>
        <title>Your Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session &&
      <div style={profileContainerStyles}>
        <div style={avatarPosition}> 
          <div style={{paddingTop: '50px'}}></div>
          <Avatar size="xxlarge" src={session.user.image} referrerpolicy='no-referrer'/>
        </div>
        <div css={profileTitleStyles}>{session.user.name}</div>

        <div css={informationStyles}><b>Email</b> {session.user.email}</div>
        <div css={informationStyles}><b>Vaccination (doses)</b> {vaccinationStatus}</div>
        <VaccinationForm user={session.user} onChange={setvaccinationStatus}/>
      
      </div>
    }
    </Layout>
  )
}