/** @jsxRuntime classic */
/** @jsx jsx */
import { css, jsx } from '@emotion/react';
import Head from 'next/head';
import Link from 'next/link'

import Button from '@atlaskit/button';

import Layout from '../../components/layout';

const buttonStyles = css({
  margin: '18px',
})

export default function EventView() {
  return (
    <Layout pageTitle="Event View">
      <Head>
        <title>View Event</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <sub>Event View Page</sub>
      <h1>View your event</h1>
      <p>
        <Link href="/home">
            <Button css={ buttonStyles }>Home</Button>
        </Link>
      </p>
    </Layout>
  )
}